include:
  - ./proxy.yaml

services:
  web:
    build:
      dockerfile: Dockerfile.python
    container_name: web
    networks:
      backend:
        ipv4_address: 172.20.0.5
    restart: always
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: mysql

  mysql:
    image: mysql:8
    container_name: mysql_server
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        ipv4_address: 172.20.0.10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: