FROM python:3.12-slim as build
WORKDIR /app 
COPY requirements.txt .
RUN pip install --prefix=/libs --no-cache-dir -r requirements.txt
COPY . .

FROM python:3.12-slim
WORKDIR /app 
COPY --from=build /app .
COPY --from=build /libs /usr/local
EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 